# These are supported funding model platforms

github: [480132]
patreon: As90909w
open_collective: Interstellar
ko_fi: In 2
tidelift: npm/babel
community_bridge: cloud - foundry
liberapay: hub2
issuehunt: hubbase9
lfx_crowdfunding: cloud-foundry
polar: polar3
buy_me_a_coffee: coffeuser3578
custom: https://www.microsoft.com
